defaultContentLanguage = "en"
ignoreFiles = ["\\.files/README.md$", "content/intermediate/260_weave_flux/app.files/"]
languageCode = "en-us"
theme = "learn"
title = "Amazon EKS Workshop"
uglyurls = false
# googleAnalytics = "UA-44634850-4"
relativeURLs = true
sectionPagesMenu = "main"

[blackfriday]
hrefTargetBlank = true

[params]
author = "Brent Langston"
branch = "main"
description = "Amazon EKS Workshop"
disableAssetsBusting = false
disableInlineCopyToClipBoard = true
disableLanguageSwitchingButton = true
disableSearch = false
disableShortcutsTitle = false
editURL = "https://github.com/aws-samples/eks-workshop/edit/main/content/"
ghrepo = "https://github.com/aws-samples/eks-workshop/"
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "tango"
pygmentsUseClasses = true
showVisitedLinks = false
template_bucket = "eksworkshop.com"
themeVariant = "mine"

#

[menu]
[[menu.main]]
identifier = "Prerequisites"
name = "This is the Mu track"
title = "Workshop using Mu"
url = "/mu/"
weight = -110

[outputs]
home = ["HTML", "JSON"]
page = ["HTML"]
